alert if version number and date do not match

diff --git a/regen b/regen
--- a/regen
+++ b/regen
@@ -1,6 +1,19 @@
 #!/bin/bash
 filepath="$1"
 
+
+function check_version() {
+  fname=$1
+
+  version=`grep -E '^version: ' $fname | awk '{print $2}'`
+  if [ "$version" != "" ] ; then
+    grep -qE "^$version [0-9]{4}-[0-9]{2}-[0-9]{2}" $fname
+    if [ "$?" != "=" ] ; then
+      echo "ERROR: Could not find version number and release date"
+    fi
+  fi
+}
+
 echo "$filepath" |grep -Eq '\.md$'
 if [ "$?" == "0" ] ; then
   # should we write it to a PDF dir
@@ -17,6 +30,11 @@ if [ "$?" == "0" ] ; then
       OUTPUT="$f.pdf"
     fi
   fi
+
+
+
+  check_version $filepath
+
 
   OUT=`ct2 -p -c "$filepath" -v $OUTPUT`
   echo "Procesed to $OUT"
